costmap_node:
   ros__parameters:
    costmap:
      resolution: 0.15
      width: 300
      height: 300

      origin:
        position:
          x: -25.0
          y: -25.0
        orientation:
          w: 1.0
      inflation radius: 8

